### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-css-intro-iMnt09#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-css-intro-iMnt09/) and meets the following criteria:

- [x] Your project is built off [this base HTML and CSS](https://gist.github.com/chrisvfritz/279c36ab6e2301e8a35526be028d8a32) (you may modify both pages however you want, e.g. adding classes or more elements)
- [x] The website looks (nearly) identical to [this mockup](https://i.imgur.com/pGemyxp.png) in the Chrome web browser -- colors must be exact, spacing/sizes should be within about `5px` (use the _Page Ruler_ extension to measure exact sizes/spacing; you might need to open the image in a new tab)
- [x] Any CSS selectors or properties may be used, though the project is possible using only what you saw in the lesson
- [x] No spacing HTML (e.g. `<br>`, `&amp;nbsp;`) is added to `index.html`
- [x] Add at least one link (`a` element) to the page and style them to be `purple` normally, but turn `orange` on hover

**Comment by stuartpearman** [comment]
Hi William,

We're looking for a pretty close match here. No need to resize the body, all the CSS from the base styles is correct and should be a good starting point to go off of.

What I would do to make this a little easier is open the image in a new tab and set the width of the browser to be the same as the width of the imgur image. Then you can more easily eye-ball the sizes and spacing and adjust accordingly.

Some things to tweak:

1. Color on your borders
2. font-weight on headings
3. width/height of your `img` tags

That'll be a good start and we can go from there!

See you in class!

**Comment by lordcrekit** [comment]
Okay, this one should be a lot closer.

Is there any easier way to get to the chrome color picker? I had to define a background color just to get to  the tool, which seems really unnecessary especially when dealing with images!

**Comment by stuartpearman** [comment]
Huh, I guess I'm not sure what you mean. You had to define a background color?

I use an extension called [Colorzilla](https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp?hl=en). I prefer it slightly to the one referenced in the lessons.

With a normal website, you can also use the element inspector.

This looks good though! :shipit:

**Comment by lordcrekit** [comment]
Can't use extensions on my work computer. Chromium won't load them.

On Apr 11, 2017 22:19, "Stuart Pearman" <notifications@github.com> wrote:

Huh, I guess I'm not sure what you mean. You had to define a background
color?

I use an extension called Colorzilla
<https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp?hl=en>.
I prefer it slightly to the one referenced in the lessons.

With a normal website, you can also use the element inspector.

This looks good though! [image: :shipit:]

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lordcrekit/MI-449-SS17-740-css-intro-iMnt09/issues/1#issuecomment-293453321>,
or mute the thread
